import Head from 'next/head'
import {Fragment} from "react";
import Layout from "../../components/Layout";
import BlogPostDetails from "../../components/blog/BlogPostDetails";

export default function BlogPostDetailsPage({post}) {
    return (
        <Fragment>
            <Head>
                <title>Morabica Blog Post Details</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <BlogPostDetails post={post} />
            </Layout>
        </Fragment>
    )
}

export async function getServerSideProps(context) {
    const {slug} = context.params;
    const res = await fetch(`${process.env.NEXT_PUBLIC_API}/posts/${slug}`)
    const post = await res.json()

    if (!post) {
        return {
            notFound: true,
        }
    }

    return {
        props: {post},
    }
}