import Head from 'next/head'
import {Fragment} from "react";
import Layout from "../../components/Layout";
import CardDetails from "../../components/cards/CardDetails";

export default function CardDetailsPage() {
    return (
        <Fragment>
            <Head>
                <title>Morabica Blog Post Details</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <CardDetails />
            </Layout>
        </Fragment>
    )
}
