import Head from 'next/head'
import {Fragment} from "react";
import CardList from "../../components/cards/CardList";
import Layout from "../../components/Layout";

export default function CardsPage() {
  return (
    <Fragment>
      <Head>
        <title>Morabica Cards</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Layout>
            <CardList />
        </Layout>
    </Fragment>
  )
}
