import Head from 'next/head'
import {Fragment} from "react";
import CardList from "../../components/cards/CardList";
import Layout from "../../components/Layout";
import Link from "next/link";
import useSWR from "swr";

const fetcher = (url) => fetch(url).then((res) => res.json())

export default function CardsPage() {
    const {data: data, error} = useSWR('http://localhost:8020/posts', fetcher)

    if (error) return <div>failed to load</div>
    if (!data) return <div>loading...</div>

    console.log('data', data);

    return (
        <Fragment>
            <Head>
                <title>Morabica Cards</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Layout>
                <Link href={"/cards/categories"}><a>view all categories</a></Link>
                <CardList cards={data["hydra:member"]} total={data["hydra:totalItems"]}/>
            </Layout>
        </Fragment>
    )
}
