import Head from 'next/head'
import {Fragment} from "react";
import Layout from "../../../components/Layout";
import BlogPostDetails from "../../../components/blog/BlogPostDetails";
import PodcastEpisodeDetails from "../../../components/podcasts/PodcastEpisodeDetails";

export default function PodcastEpisodeDetailsPage() {
    return (
        <Fragment>
            <Head>
                <title>Morabica Blog Post Details</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <PodcastEpisodeDetails />
            </Layout>
        </Fragment>
    )
}
